
package com.wordpress.erenha.java.desktop.entry.view;

/**
 *
 * @author Irfan Hidayat Amarulloh
 */
public class MainFrame extends javax.swing.JFrame {

    private static MainFrame instance;

    public static MainFrame getInstance() {
        if(instance == null){
            instance = new MainFrame();
        }
        return instance;
    }
    
    /**
     * Creates new form MainFrame
     */
    private MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEntry1 = new com.wordpress.erenha.java.desktop.entry.view.PanelEntry();
        panelLogin = new com.wordpress.erenha.java.desktop.entry.view.PanelLogin();
        panelEntry = new com.wordpress.erenha.java.desktop.entry.view.PanelEntry();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Entry Mahasiswa");
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(panelLogin, "card2");
        getContentPane().add(panelEntry, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainFrame.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wordpress.erenha.java.desktop.entry.view.PanelEntry panelEntry;
    private com.wordpress.erenha.java.desktop.entry.view.PanelEntry panelEntry1;
    private com.wordpress.erenha.java.desktop.entry.view.PanelLogin panelLogin;
    // End of variables declaration//GEN-END:variables
}
